<center><img src="https://amitness.com/posts/images/i-am-groot-sentence.png"><br>
<img src="https://thumbs.dreamstime.com/b/arrow-down-shadow-icon-white-background-flat-style-arrow-down-icon-your-web-site-design-logo-app-ui-arrow-symbol-arrow-138100161.jpg?w=768" width="100" height="100"><br>
<img src="https://amitness.com/posts/images/i-am-groot-embedding.png"><br>
<img src="https://thumbs.dreamstime.com/b/arrow-down-shadow-icon-white-background-flat-style-arrow-down-icon-your-web-site-design-logo-app-ui-arrow-symbol-arrow-138100161.jpg?w=768" width="100" height="100"><br>
<img src="https://amitness.com/posts/images/rnn-default-keras.png"width="600" height="600"></center>

In [1]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/datasets/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews/IMDB Dataset.csv


In [2]:
import pandas as pd 
import numpy as np 

import tensorflow as tf
import keras
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences

In [3]:
df = pd.read_csv('/kaggle/input/datasets/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews/IMDB Dataset.csv')
df.head()

,review,sentiment
0,One of the other reviewers has mentioned that ...,positive
1,A wonderful little production. <br /><br />The...,positive
2,I thought this was a wonderful way to spend ti...,positive
3,Basically there's a family where a little boy ...,negative
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive


In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB


In [5]:
df.isna().sum().sum()

np.int64(0)

In [6]:
print(df.iloc[:5,:1])

                                              review
0  One of the other reviewers has mentioned that ...
1  A wonderful little production. <br /><br />The...
2  I thought this was a wonderful way to spend ti...
3  Basically there's a family where a little boy ...
4  Petter Mattei's "Love in the Time of Money" is...


In [7]:
# integer tokenize the reviews
tokenizer = Tokenizer()

tokenizer.fit_on_texts(df['review'])

sequences = tokenizer.texts_to_sequences(df['review'])
sequences = pad_sequences(sequences,padding='post')
print(sequences[:5])

[[   27     4     1 ...     0     0     0]
 [    3   393   120 ...     0     0     0]
 [   10   190    11 ...     0     0     0]
 [  688   222     3 ...     0     0     0]
 [71841 33192   112 ...     0     0     0]]


In [8]:
X = sequences

In [9]:
max_len = max(len(seq) for seq in sequences)

print("Maximum sequence length:", max_len)

Maximum sequence length: 2493


In [10]:
print("total Vocabulary: ",len(tokenizer.word_index))

total Vocabulary:  124252


In [11]:
# model building
model = Sequential()

model.add(Embedding(124253,output_dim=2,input_length=5))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.compile(optimizer='adam',metrics=['accuracy'])

predict = model.predict(X)
# embeddings
print(predict[:5])

2026-08-06 14:01:10.760660: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


1563/1563 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step
[[[-0.03497182 -0.0458136 ]
  [ 0.00138863  0.04180345]
  [-0.01913795  0.03328551]
  ...
  [-0.01832085 -0.01510999]
  [-0.01832085 -0.01510999]
  [-0.01832085 -0.01510999]]

 [[ 0.04684479  0.02742635]
  [ 0.01742889 -0.02347713]
  [ 0.00953645  0.0199351 ]
  ...
  [-0.01832085 -0.01510999]
  [-0.01832085 -0.01510999]
  [-0.01832085 -0.01510999]]

 [[-0.04174739  0.01344435]
  [-0.04056484  0.01466807]
  [-0.01099097  0.00898191]
  ...
  [-0.01832085 -0.01510999]
  [-0.01832085 -0.01510999]
  [-0.01832085 -0.01510999]]

 [[-0.03913286  0.04839518]
  [-0.04204857  0.03703738]
  [ 0.04684479  0.02742635]
  ...
  [-0.01832085 -0.01510999]
  [-0.01832085 -0.01510999]
  [-0.01832085 -0.01510999]]

 [[-0.03267676 -0.0114005 ]
  [-0.00135095  0.04649464]
  [ 0.03704757 -0.04444447]
  ...
  [-0.01832085 -0.01510999]
  [-0.01832085 -0.01510999]
  [-0.01832085 -0.01510999]]]
